export const wedding = {
  groom: '汪家喆',
  bride: '朱敏',
  date: '2026.10.03',
  dateLong: '2026 年 10 月 3 日',
  lunar: '农历八月廿三',
  day: '星期六',
  venue: '黄山市歙县徽苑一楼',
  room: '2号厅',
  address: '黄山市歙县徽苑一楼，2号厅',
  welcome: '17:28',
  ceremony: '17:58',
};

export const photographs = [
  {
    src: 'courtyard',
    original: '5A8A5952.jpg',
    width: 5334,
    height: 7997,
    label: '在你身旁',
    index: '01',
    caption: '人间的风景很多，\n我偏爱有你的这一处。',
    paper: 'letter',
    carrier: '一封信笺',
    alt: '朱敏身穿红色长裙，与汪家喆在中式庭院相望',
    position: '50% 46%',
  },
  {
    src: 'promise',
    original: '5A8A1204.jpg',
    width: 5464,
    height: 8192,
    label: '把爱写成日常',
    index: '02',
    caption: '那些平凡的小事，\n因为是你，都值得珍藏。',
    paper: 'memo',
    carrier: '一页日常',
    alt: '朱敏身穿白色婚纱，与汪家喆携手站在暖灰色背景前微笑',
    position: '50% 50%',
  },
  {
    src: 'together',
    original: '5A8A6497.jpg',
    width: 5334,
    height: 7997,
    label: '往后的每一页',
    index: '03',
    caption: '不用赶路。\n往后的日子，我们慢慢走。',
    paper: 'postcard',
    carrier: '一张明信片',
    alt: '朱敏手捧白花，与汪家喆依偎坐在花园的木椅上',
    position: '50% 35%',
  },
  {
    src: 'rose-room',
    original: '5A8A1854.jpg',
    width: 5464,
    height: 8192,
    label: '把时光坐暖',
    index: '04',
    caption: '阳光在木地板上慢慢走。\n我靠近你，\n一个寻常的午后，就有了余生的模样。',
    paper: 'rose',
    carrier: '一张午后便笺',
    alt: '朱敏身穿粉色婚纱，依偎在汪家喆身旁，两人坐在木地板房间的花与沙发之间',
    position: '50% 48%',
  },
  {
    src: 'a-long-way',
    original: '5A8A6596.jpg',
    width: 8021,
    height: 5350,
    label: '都想和你一起',
    index: '05',
    caption: '这一页写我们，\n下一页，想请你也在场。',
    paper: 'book',
    carrier: '一页余生',
    alt: '汪家喆与朱敏在绿色草坪上牵手相望，朱敏轻扬白色捧花',
    position: '50% 35%',
  },
];
export const letterNotes = [
  {
    label: '一纸短，情意长',
    caption:
      '把平凡的日子，\n过成我们的日子。\n\n也把这份欢喜，\n郑重地交给你。',
  },
  {
    label: '共赴我们的婚礼',
    caption: `${wedding.dateLong} · ${wedding.day}\n${wedding.lunar}\n${wedding.welcome} 到场 · ${wedding.ceremony} 仪式\n${wedding.venue}\n${wedding.room}`,
  },
  {
    label: '汪家喆 & 朱敏',
    caption: '有你在，才是圆满。\n诚邀你，与我们一起，\n开启人生的新一页。',
  },
  {
    label: '致 · 亲爱的你',
    caption: '有些欢喜，想当面说。\n\n有些时刻，想与你一起。',
  },
];
